# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Programación Internet - Universidad de Lima
email: hquintan@ulima.edu.pe
description: > # this means to ignore newlines until "baseurl:"
  Información del curso programación Internet
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: hquintana
github_username:  jsatch

# Build settings
markdown: kramdown
